#!/usr/bin/env bash
#Install nginx on your server

sudo apt update

sudo apt install -y nginx

sudo update-rc.d nginx defaults

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i 's|root /var/www/html;|root /var/www/html;|' /etc/nginx/sites-available/default

sudo sed -i 's|index .*|index index.html;|' /etc/nginx/sites-available/default

sudo sed -i '/listen 80 default_server/a \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i '/server {/a \    error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
