#!/usr/bin/env bash
#load balancer configurations

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 527474-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 527474-web-02 100.26.17.68:80 check\n\tserver 527474-web-01 100.25.109.145:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy start

