#!/usr/bin/env bash
#Configures nginx to listen to port 80
sudo sed -i 's|listen [0-9]*;|listen 80;|' /etc/nginx/sites-available/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
